---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  name: hwakabh-childapp-bob
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/hwakabh/argocd-minimal-sample.git'
    path: k8s-manifests/childapp-bob
    targetRevision: HEAD
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: childapp-bob
