---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: canary-nginx-alice
  namespace: childapp-alice
  labels:
    name: app
    color: green
spec:
  minReadySeconds: 30
  strategy:
    type: RollingUpdate
  replicas: 3
  selector:
    matchLabels:
      color: green
      name: app
  template:
    metadata:
      name: green
      labels:
        name: app
        color: green
    spec:
      containers:
      - image: nginx:latest
        name: nginx-alice
        ports:
          - containerPort: 80
        volumeMounts:
        - name: www
          mountPath: /var/www
      volumes:
      - name: www
        persistentVolumeClaim:
          claimName: pvc-alice-www
