---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blue-nginx-alice
  labels:
    name: app
    color: blue
spec:
  minReadySeconds: 30
  strategy:
    type: RollingUpdate
  replicas: 3
  selector:
    matchLabels:
      color: blue
      name: app
  template:
    metadata:
      name: blue
      labels:
        name: app
        color: blue
    spec:
      containers:
      - image: docker.io/hiraiy7i/hwakabhcitest:a5bb363edc7e656270bed8f4ee0e3a15658744ab
        name: nginx-alice
        ports:
          - containerPort: 80

