---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blue-nginx-alice
  labels:
    name: app
    color: blue
spec:
  minReadySeconds: 30
  strategy:
    type: RollingUpdate
  replicas: 3
  selector:
    matchLabels:
      color: blue
      name: app
  template:
    metadata:
      name: blue
      labels:
        name: app
        color: blue
    spec:
      containers:
      - image: docker.io/wakabh56/hwakabhcitest:f4922f57fedc4de3c98aa23582e0ccb51b31d81f
        name: nginx-alice
        ports:
          - containerPort: 80

