---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-www
spec:
  # Required enabling extraMounts in kind config
  storageClassName: standard
  hostPath:
    path: /www/
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-alice-www
spec:
  volumeName: pv-www
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
